### ISSUE TITLE
From AdditionalsStep

### ISSUE THREAD

**Issue by YuliaKletsova** [ledenev-viktor/music-studio#51]
<img width="623" alt="image" src="https://github.com/ledenev-viktor/music-studio/assets/48691234/634e527d-33ed-4e08-b80f-94c34fbb214e">

above the comment add checkboxes for 
- двойная педаль (кардан) 10 ₾/hour
- тарелка China 10 ₾/hour
- бас-гитара 4-струнная Harley Benton 10 ₾/hour
- электропианино Thomann DP-28 10 ₾/hour

**Comment by YuliaKletsova** [comment]
Also think how to add to 
<img width="634" alt="image" src="https://github.com/ledenev-viktor/music-studio/assets/48691234/7fc72cf8-9bb9-4fbc-9c29-9586b25b2e67">

**Comment by ledenev-viktor** [comment]
added checkboxes optional equipment
