### ISSUE TITLE
Create event in google calendar on approve

### ISSUE THREAD

**Issue by YuliaKletsova** [ledenev-viktor/music-studio#65]
Before implementation let's discuss it together

**Comment by YuliaKletsova** [comment]
Please do not merge untill we show it to "stakeholders"

**Comment by YuliaKletsova** [comment]
Take a look here first https://www.youtube.com/watch?v=kNwCT5PN93k&t=801s

**Comment by ledenev-viktor** [comment]
1. Статус подтвердить - показываем модалку - сделано
2. После ок в модалке, нужно создавать событие в календаре
3. Если событие не создалось, то нужно показать ошибку - тост: создать событие не удалось
4. Если создалось, то в supabase поменять статус на approved
5. Записать ссылку на google-event.

**Comment by ledenev-viktor** [comment]
https://github.com/ledenev-viktor/music-studio/pull/97
