### ISSUE TITLE
Create a form

### ISSUE THREAD

**Issue by YuliaKletsova** [ledenev-viktor/music-studio#8]
Create a form screen 

https://www.figma.com/file/qGzhPxVvjK1lkG3GaDWFdF/Praktika?type=design&node-id=904%3A24&mode=design&t=B5WAU6SSJNZHZdy8-1

BLOCKED BY https://github.com/ledenev-viktor/music-studio/issues/9
BLOCKED BY https://github.com/ledenev-viktor/music-studio/issues/13

**Comment by ledenev-viktor** [comment]
created a new branch based on styled-pages => form-page, merged it with the form branch
https://github.com/ledenev-viktor/music-studio/tree/form-page

**Comment by YuliaKletsova** [comment]
DONE
